#!/usr/bin/env bash

# Place all necessary folders and files on the filesystem for development

# Local variables for referencing project folders:
repo_automation="`dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )`"
repo_copy="$repo_automation/copy"
repo_link="$repo_automation/link"
repo_source="$repo_automation/source"

# Create the .automation file structure to hold all hidden environment files:
mkdir ~/.automation
mkdir ~/.automation/bin
mkdir ~/.automation/link

# Make hidden variables and directories files if they do not exist:
if [[ ! -f ~/.vars ]]; then cp "$repo_copy/.vars" ~/.vars ; fi
if [[ ! -f ~/.dirs ]]; then cp "$repo_copy/.dirs" ~/.dirs ; fi

# Create a directory for Sublime Text projects:
mkdir ~/Sublime_Projects

# Create a Workspace directory for all business projects:
mkdir ~/Workspace

# Copy Sublime preference files:
cp "$repo_copy/Package Control.sublime-settings" ~/"Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings"
cp "$repo_copy/Preferences.sublime-settings" ~/"Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"

# Copy scopes file for reference:
cp "$repo_copy/snippet_scopes" ~/.automation/

# Copy all source files:
rsync -av --progress "$repo_source" ~/.automation